name: Test workflow
#on:
#  push:
#    branches:
#      - master
on:
  milestone:
    types: [closed]
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Release Notes
        uses: docker://decathlon/release-notes-generator-action:2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: temp_release_notes
          USE_MILESTONE_TITLE: "true"
#      - name: Test
#        id: test
#        run: php --version
#clone
#run php script (php works is installed in container)
# update release notes using actions/release-notary
