on: push
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}