name: Create Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag and prepare release
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Update release notes
#        uses: Roang-zero1/github-create-release-action@master
#      - name: Build assets
#      - name: Upload assets