name: Create Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build assets
        run: echo "Assets built!"
      - name: Verify Changelog
        run: echo "Verify if Changelog has correct version header"
      - name: Tag and prepare release
        id: tag_and_prepare_release
        uses: serucee/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Update release notes
#        uses: Roang-zero1/github-create-release-action@master
#      - name: Build assets
#      - name: Upload assets