name: Create release # name displayed in the web interface
on:
  pull_request:
    types: [closed]

jobs: # contains all jobs
  prepare:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'RC')
    steps:
      - uses: actions/checkout@v1
      - name: Define bump for version
        env:
          VERSION_BUMP: ${{ github.hread_ref }}
        run: |
          echo "$VERSION_BUMP" > version.txt
          sed -i "s/RC-//g" version.txt
          sed -i "s/major//g" version.txt
          sed -i "s/minor//g" version.txt
          sed -i "s/patch//g" version.txt
      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: master
          DEFAULT_BUMP: ${{ bump.version }}
      - name: Build Package
        run: zip -r package.zip collection
      - name: Create release notes
        run: echo "test" > body.md # use our current script to create those
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "package.zip"
          bodyFile: "body.md"
          tag: ${{ steps.create_tag.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}