name: Create Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tag and prepare release
        id: tag_and_prepare_release
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #0b745af2a502b8338c203a938a0d7bfaadb2378b
      - uses: actions/checkout@master
      - name: Build assets
        if: ${{ steps.tag_and_prepare_release.outputs.tag }}
        run: echo "Assets built!"
      - name: Verify Changelog
        if: ${{ steps.tag_and_prepare_release.outputs.tag }}
        run: echo "Verify if Changelog has correct version header"
      - name: Upload release notes and package
        if: ${{ steps.tag_and_prepare_release.outputs.tag }}
        uses: Roang-zero1/github-create-release-action@master
        with:
          update_existing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Update release notes
#        uses: Roang-zero1/github-create-release-action@master
#      - name: Build assets
#      - name: Upload assets