name: Test workflow # name displayed in the web interface
on: push # what triggers this workflow

jobs: # contains all jobs
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: master
          DEFAULT_BUMP: patch
      - name: Build Package
        run: zip -r package.zip collection
      - name: Create release notes
        run: echo "test" > body.md # use our current script to create those
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "package.zip"
          bodyFile: "body.md"
          tag: ${{ steps.create_tag.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}