name: Test release workflow # name displayed in the web interface
on: push # what triggers this workflow

jobs: # contains all jobs
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Test echo
        run: echo "Hello World!"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
#      - name: Create empty tag and release
#        id: create_tag
#        uses: anothrNick/github-tag-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          RELEASE_BRANCHES: master
#          DEFAULT_BUMP: patch
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 0.0.2
          release_name: 0.0.2
          body: testbody
          draft: true