name: Update release notes # name displayed in the web interface
on:
  push:
    tags:
      - "v*"

jobs: # contains all jobs
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Release Notary
        uses: commitsar-app/release-notary@v0.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}